- url: https://app.datadoghq.com/watchdog
  title: Watchdog
- url: https://app.datadoghq.com/event/explorer
  title: Eventt Explorers
- url: https://app.datadoghq.com/dashboard
  title: Dashboards
- url: https://app.datadoghq.com/infrastructure
  title: Infrastructure Host List
- url: https://app.datadoghq.com/containers
  title: Infrastructure Containers
- url: https://app.datadoghq.com/orchestration/overview/deployment
  title: Infrastructure Deployment
- url: https://app.datadoghq.com/orchestration/overview/pod
  title: Infrastructure Pod
- url: https://app.datadoghq.com/infrastructure/map
  title: Infrastructure Map
- url: https://app.datadoghq.com/monitors/manage
  title: Monitors
- url: https://app.datadoghq.com/monitors#/downtime
  title: Monitor Downtime
- url: https://app.datadoghq.com/metric/explorer
  title: Metrics Explorers
- url: https://app.datadoghq.com/metric/summary
  title: Metrics Summary
- url: https://app.datadoghq.com/account/settings
  title: Integration
- url: https://app.datadoghq.com/account/settings#api
  title: Integration api
- url: https://app.datadoghq.com/services
  title: Service Catalog
- url: https://app.datadoghq.com/notebook/list
  title: Notebooks
- url: https://app.datadoghq.com/logs
  title: Logs
- url: https://app.datadoghq.com/synthetics/list
  title: Synthetics
- url: https://app.datadoghq.com/rum/list
  title: RUM Application
- url: https://app.datadoghq.com/account/usage
  title: Plan & Usage
- url: https://app.datadoghq.com/slo/manage
  title: SLO
- url: https://app.datadoghq.com/infrastructure/catalog
  title: Resource Catalog
- url: https://app.datadoghq.com/cost/overview
  title: Cloud Costs
